// Reduce FS-UAE (Barto remote debugger) `monitor profile` captures of the
// TRACE_CODE Amiga build to attributable totals. Every executed instruction is
// recorded by the emulator with its cycle cost and pre-instruction registers;
// nothing is sampled and the traced executable contains no observer.
//
//   trace_reduce CONFIG OUTDIR TRACE... [--fields FIRST LAST]
//
// CONFIG (generated by host/native_trace.py) lists hunk-relative native code
// facts: handler entries and their kinds, call instructions, RTE sites, the
// Board storage offset and event addresses. Outputs are TSV tables in OUTDIR.
// PCs outside the first code hunk and Kickstart are not recorded by FS-UAE.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace {
constexpr uint32_t Marker = 0x7fffffff;
constexpr uint32_t None = 0xffffffff;       // unrecorded PC
struct Frame {uint32_t callee, sp;};
struct Context {
    int kind;                 // handler kind index, -1 guest/unknown root
    int top;                  // outermost kind of this nesting chain
    uint32_t guestPc;         // guest PC that was interrupted (canonical)
    bool full;                // reached the full C dispatcher
    uint64_t cycles;          // own cycles, excluding nested contexts
    uint32_t prevPc, prevSp;
    std::vector<Frame> stack;
};
struct Site {uint64_t count=0,cycles=0,full=0,fullCycles=0;};
struct Counter {uint64_t self=0,incl=0,calls=0;};

std::vector<std::string> kinds;
std::unordered_map<uint32_t,int> entries;      // native handler entry -> kind
std::unordered_map<uint32_t,int> kickEntries;  // absolute Exec vector targets
std::unordered_map<uint32_t,uint32_t> calls;   // call instruction -> fall-through
std::unordered_set<uint32_t> rtes;
std::unordered_map<uint32_t,int> events;       // native address -> event index
std::unordered_map<uint32_t,int> guestEvents;  // canonical guest PC -> event index
std::vector<std::string> eventNames;
uint32_t guestOffset=0,textSize=0,fullDispatch=None;
uint32_t delayFirst=0x2442,delayLast=0x2446;
std::vector<uint16_t> kick;                    // Kickstart words from the capture header

// Per-field categories: 0 guest delay loop, 1 other guest, 2 unknown/other
// root, then kinds as top-level services, then kinds as nested contexts.
unsigned categoryCount(){return 3+2*kinds.size();}

bool isKick(uint32_t pc){return pc>=0xf80000 && pc<0x1000000;}
bool kickRte(uint32_t pc){
    if(!isKick(pc) || kick.empty())return false;
    uint32_t i=(pc-0xf80000)>>1;return i<kick.size() && kick[i]==0x4e73;
}

void readConfig(const char *path){
    std::ifstream in(path);if(!in){fprintf(stderr,"cannot read %s\n",path);exit(1);}
    std::string line;
    while(std::getline(in,line)){
        std::istringstream s(line);std::string key;s>>key;
        if(key=="kind"){std::string name;s>>name;kinds.push_back(name);}
        else if(key=="entry"){uint32_t a;int k;s>>std::hex>>a>>std::dec>>k;entries[a]=k;}
        else if(key=="kickentry"){uint32_t a;int k;s>>std::hex>>a>>std::dec>>k;kickEntries[a]=k;}
        else if(key=="call"){uint32_t a,n;s>>std::hex>>a>>n;calls[a]=n;}
        else if(key=="rte"){uint32_t a;s>>std::hex>>a;rtes.insert(a);}
        else if(key=="guest"){s>>std::hex>>guestOffset;}
        else if(key=="text"){s>>std::hex>>textSize;}
        else if(key=="full"){s>>std::hex>>fullDispatch;}
        else if(key=="delay"){s>>std::hex>>delayFirst>>delayLast;}
        else if(key=="event"){uint32_t a;std::string n;s>>std::hex>>a>>n;events[a]=eventNames.size();eventNames.push_back(n);}
        else if(key=="gevent"){uint32_t a;std::string n;s>>std::hex>>a>>n;guestEvents[a]=eventNames.size();eventNames.push_back(n);}
    }
}

struct Reader {
    std::vector<uint8_t> data;size_t off=0;
    uint32_t word(){
        if(off+4>data.size()){fprintf(stderr,"truncated trace\n");exit(1);}
        uint32_t v;memcpy(&v,&data[off],4);off+=4;return v; // little-endian host
    }
    void skip(size_t n){if(off+n>data.size()){fprintf(stderr,"truncated trace\n");exit(1);}off+=n;}
};

// Aggregates
uint32_t selectedSite=None;
uint64_t selectedCycles=0;
std::unordered_map<uint32_t,Counter> siteCounters;
std::unordered_map<uint32_t,Counter> nativeCounters;  // hunk-relative pc / callee
std::unordered_map<uint64_t,uint64_t> edges;           // (parent callee | root id) << 32 | child callee
std::unordered_map<uint64_t,uint64_t> selfByKindPc;    // (nested<<63 | kind<<32 | pc) -> cycles
std::unordered_map<uint32_t,uint64_t> kickSelf;
std::vector<uint64_t> guestSelf(0x40000);              // word-indexed canonical guest PC
std::map<std::pair<int,uint32_t>,Site> sites;         // (kind, guest pc) top-level episodes
std::unordered_map<uint32_t,uint64_t> rootIncl;        // kind -> own cycles incl. calls
uint64_t unrecorded[2]={}; // [top-level service, nested]
std::vector<uint64_t> entryMarker;                    // exception-entry cycles by kind
FILE *fieldOut=nullptr;
uint64_t totalCycles=0,totalIdle=0,totalFields=0;

void finishEpisode(Context &c){
    if(c.kind<0 || !c.cycles)return; // outside the selected field window
    Site &s=sites[{c.kind,c.guestPc}];
    ++s.count;s.cycles+=c.cycles;if(c.full){++s.full;s.fullCycles+=c.cycles;}
}

void reduce(const char *path,uint32_t first,uint32_t last,uint32_t &globalField){
    Reader r;
    {
        FILE *f=fopen(path,"rb");if(!f){fprintf(stderr,"cannot open %s\n",path);exit(1);}
        fseek(f,0,SEEK_END);long n=ftell(f);fseek(f,0,SEEK_SET);r.data.resize(n);
        if(fread(r.data.data(),1,n,f)!=size_t(n)){fprintf(stderr,"read failed\n");exit(1);}fclose(f);
    }
    uint32_t fields=r.word(),sectionCount=r.word();
    std::vector<uint32_t> sections(sectionCount);for(auto &s:sections)s=r.word();
    r.skip(16);
    for(int i=0;i<3;++i){
        uint32_t size=r.word();
        if(i==0 && size==0x80000 && kick.empty()){
            kick.resize(size/2);
            for(uint32_t w=0;w<size/2;++w)kick[w]=uint16_t(r.data[r.off+2*w]<<8|r.data[r.off+2*w+1]);
        }
        r.skip(size);
    }
    r.word();r.word(); // base clock, cycle unit
    const unsigned categories=categoryCount();
    for(uint32_t field=0;field<fields;++field,++globalField){
        uint32_t custom=r.word();if(custom!=520){fprintf(stderr,"custom block %u\n",custom);exit(1);}r.skip(custom);
        uint32_t aga=r.word();if(aga!=0 && aga!=1024){fprintf(stderr,"AGA block %u\n",aga);exit(1);}r.skip(aga);
        for(int i=0;i<2;++i){uint32_t size=r.word(),count=r.word();r.skip(size_t(size)*count);}
        uint32_t cycles=r.word(),idle=r.word(),count=r.word();
        size_t end=r.off+size_t(4)*count;
        const bool keep=globalField>=first && globalField<=last;
        std::vector<uint64_t> category(categories);
        std::vector<uint64_t> eventCount(eventNames.size());
        // Each capture starts at an arbitrary boundary; the first guest PC
        // resynchronizes nesting (original code only runs at depth zero).
        static std::vector<Context> contexts;
        if(field==0){contexts.clear();contexts.push_back(Context{-1,-1,None,false,0,None,0,{}});}
        uint64_t pending=0,accounted=0;uint32_t lastGuest=None;
        while(r.off<end){
            uint32_t pc=None,v;
            for(;;){v=r.word();if(v>=0xffff0000)break;if(pc==None)pc=v;}
            uint32_t cost=0xffffffff-v;
            uint32_t sp;memcpy(&sp,&r.data[r.off+15*4],4);
            r.skip(68);accounted+=cost;
            if(pc==Marker){pending+=cost;continue;}
            // Region and exception entry.
            const bool guest=pc!=None && pc>=guestOffset && pc-guestOffset<0x80000;
            const bool kickPc=pc!=None && isKick(pc);
            const bool native=pc!=None && !guest && !kickPc && pc<textSize;
            int entryKind=-1;
            if(native){auto e=entries.find(pc);if(e!=entries.end())entryKind=e->second;}
            else if(kickPc){auto e=kickEntries.find(pc);if(e!=kickEntries.end())entryKind=e->second;}
            if(guest){
                // Returning to original code closes every open service context.
                while(contexts.size()>1){finishEpisode(contexts.back());contexts.pop_back();}
                contexts[0].kind=-1;contexts[0].top=-1;
            }
            Context *c=&contexts.back();
            uint64_t extra=0;
            if(entryKind>=0){
                Context n{entryKind,contexts.size()==1?entryKind:c->top,
                          contexts.size()==1?lastGuest:c->guestPc,false,0,None,sp,{}};
                contexts.push_back(n);c=&contexts.back();
                if(keep)entryMarker[entryKind]+=pending;
                extra=pending;pending=0;
            }else{extra=pending;pending=0;} // between-instruction cycles of the previous record
            const uint64_t charge=cost+extra;
            if(!keep){
                if(native && rtes.count(pc) && contexts.size()>1){finishEpisode(*c);contexts.pop_back();}
                else if(kickRte(pc) && contexts.size()>1){finishEpisode(*c);contexts.pop_back();}
                if(guest)lastGuest=pc-guestOffset;
                continue;
            }
            const bool nested=contexts.size()>2;
            // Per-field category.
            unsigned cat;
            if(guest){uint32_t g=pc-guestOffset;cat=g>=delayFirst && g<delayLast?0:1;}
            else if(c->kind<0)cat=2;
            else cat=nested?3+kinds.size()+c->kind:3+c->kind;
            category[cat]+=charge;
            if(guest){
                uint32_t g=pc-guestOffset;guestSelf[g>>1]+=charge;lastGuest=g;
                auto e=guestEvents.find(g);if(e!=guestEvents.end())++eventCount[e->second];
            }else{
                c->cycles+=charge;
                const bool selected=selectedSite!=None && !nested && c->guestPc==selectedSite &&
                    c->kind>=0 && kinds[c->kind]=="lineA";
                if(selected)selectedCycles+=charge;
                if(native){
                    if(pc==fullDispatch)c->full=true;
                    // Call stacks, per context.
                    while(!c->stack.empty() && sp>c->stack.back().sp)c->stack.pop_back();
                    if(c->prevPc!=None){
                        auto k=calls.find(c->prevPc);
                        if(k!=calls.end() && sp==c->prevSp-4 && pc!=k->second){
                            c->stack.push_back(Frame{pc,sp});++nativeCounters[pc].calls;
                            if(selected)++siteCounters[pc].calls;
                        }
                    }
                    nativeCounters[pc].self+=charge;
                    if(selected)siteCounters[pc].self+=charge;
                    uint32_t seen[64];unsigned n=0;
                    uint32_t parent=(nested?0x80:0)|uint32_t(c->kind+1);
                    for(auto &f:c->stack){edges[(uint64_t(parent)<<32)|f.callee]+=charge;parent=f.callee;}
                    edges[(uint64_t(parent)<<32)|0xfffffffe]+=charge; // self time of the innermost frame
                    for(auto &f:c->stack){
                        bool dup=false;for(unsigned i=0;i<n;++i)if(seen[i]==f.callee)dup=true;
                        if(!dup){nativeCounters[f.callee].incl+=charge;if(selected)siteCounters[f.callee].incl+=charge;if(n<64)seen[n++]=f.callee;}
                    }
                    auto e=events.find(pc);if(e!=events.end())++eventCount[e->second];
                    c->prevPc=pc;c->prevSp=sp;
                }else{
                    c->prevPc=None;
                    if(kickPc)kickSelf[pc]+=charge;else unrecorded[nested?1:0]+=charge;
                }
                if(c->kind>=0)rootIncl[uint32_t(nested?1000+c->kind:c->kind)]+=charge;
                selfByKindPc[(uint64_t(nested)<<63)|(uint64_t(uint32_t(c->kind+1))<<32)|(native?pc:kickPc?pc:None)]+=charge;
            }
            if((native && rtes.count(pc)) || kickRte(pc)){
                if(contexts.size()>1){finishEpisode(*c);contexts.pop_back();}
            }
        }
        if(r.off!=end){fprintf(stderr,"record boundary mismatch in field %u\n",field);exit(1);}
        if(accounted+100<cycles || accounted>cycles+100+cycles/1000)
            fprintf(stderr,"warning: field %u accounted %llu of %u cycles\n",field,(unsigned long long)accounted,cycles);
        uint32_t size=r.word();r.word();r.skip(size); // screenshot
        if(keep){
            totalCycles+=cycles;totalIdle+=idle;++totalFields;
            fprintf(fieldOut,"%u\t%u\t%u",globalField,cycles,idle);
            for(auto v:category)fprintf(fieldOut,"\t%llu",(unsigned long long)v);
            for(auto v:eventCount)fprintf(fieldOut,"\t%llu",(unsigned long long)v);
            fprintf(fieldOut,"\n");
        }
    }
    if(r.off!=r.data.size()){fprintf(stderr,"trailing trace data in %s\n",path);exit(1);}
}
}

int main(int argc,char **argv){
    if(argc<4){fprintf(stderr,"usage: trace_reduce CONFIG OUTDIR TRACE... [--fields FIRST LAST] [--site PC]\n");return 2;}
    readConfig(argv[1]);std::string out=argv[2];
    uint32_t first=0,last=0xffffffffu;std::vector<const char*> traces;
    for(int i=3;i<argc;++i){
        if(!strcmp(argv[i],"--fields") && i+2<argc){first=strtoul(argv[i+1],0,0);last=strtoul(argv[i+2],0,0);i+=2;}
        else if(!strcmp(argv[i],"--site") && i+1<argc){selectedSite=strtoul(argv[++i],0,0);}
        else traces.push_back(argv[i]);
    }
    entryMarker.assign(kinds.size(),0);
    fieldOut=fopen((out+"/fields.tsv").c_str(),"w");
    fprintf(fieldOut,"field\tcycles\tidle\tguest_delay\tguest_other\tother_root");
    for(auto &k:kinds)fprintf(fieldOut,"\ttop_%s",k.c_str());
    for(auto &k:kinds)fprintf(fieldOut,"\tnested_%s",k.c_str());
    for(auto &e:eventNames)fprintf(fieldOut,"\tev_%s",e.c_str());
    fprintf(fieldOut,"\n");
    uint32_t globalField=0;
    for(auto t:traces)reduce(t,first,last,globalField);
    fclose(fieldOut);
    FILE *f=fopen((out+"/native.tsv").c_str(),"w");
    fprintf(f,"pc\tself\tincl\tcalls\n");
    for(auto &n:nativeCounters)fprintf(f,"%x\t%llu\t%llu\t%llu\n",n.first,(unsigned long long)n.second.self,(unsigned long long)n.second.incl,(unsigned long long)n.second.calls);
    fclose(f);
    if(selectedSite!=None){
        f=fopen((out+"/site-native.tsv").c_str(),"w");fprintf(f,"pc\tself\tincl\tcalls\n");
        for(auto &n:siteCounters)fprintf(f,"%x\t%llu\t%llu\t%llu\n",n.first,(unsigned long long)n.second.self,(unsigned long long)n.second.incl,(unsigned long long)n.second.calls);
        fclose(f);
    }
    f=fopen((out+"/edges.tsv").c_str(),"w");fprintf(f,"parent\tchild\tcycles\n");
    for(auto &e:edges)fprintf(f,"%x\t%x\t%llu\n",uint32_t(e.first>>32),uint32_t(e.first),(unsigned long long)e.second);
    fclose(f);
    f=fopen((out+"/kind_pc.tsv").c_str(),"w");
    fprintf(f,"nested\tkind\tpc\tcycles\n");
    for(auto &n:selfByKindPc)fprintf(f,"%u\t%d\t%x\t%llu\n",unsigned(n.first>>63),int(uint32_t(n.first>>32)&0x7fffffff)-1,uint32_t(n.first),(unsigned long long)n.second);
    fclose(f);
    f=fopen((out+"/kick.tsv").c_str(),"w");fprintf(f,"pc\tcycles\n");
    for(auto &n:kickSelf)fprintf(f,"%x\t%llu\n",n.first,(unsigned long long)n.second);fclose(f);
    f=fopen((out+"/guest.tsv").c_str(),"w");fprintf(f,"pc\tcycles\n");
    for(uint32_t i=0;i<guestSelf.size();++i)if(guestSelf[i])fprintf(f,"%x\t%llu\n",i<<1,(unsigned long long)guestSelf[i]);fclose(f);
    f=fopen((out+"/sites.tsv").c_str(),"w");fprintf(f,"kind\tguest_pc\tcount\tcycles\tfull\tfull_cycles\n");
    for(auto &s:sites)fprintf(f,"%s\t%x\t%llu\t%llu\t%llu\t%llu\n",s.first.first>=0?kinds[s.first.first].c_str():"?",s.first.second,
        (unsigned long long)s.second.count,(unsigned long long)s.second.cycles,(unsigned long long)s.second.full,(unsigned long long)s.second.fullCycles);
    fclose(f);
    f=fopen((out+"/summary.tsv").c_str(),"w");
    fprintf(f,"fields\t%llu\ncycles\t%llu\nidle\t%llu\nunrecorded_top\t%llu\nunrecorded_nested\t%llu\n",(unsigned long long)totalFields,
        (unsigned long long)totalCycles,(unsigned long long)totalIdle,(unsigned long long)unrecorded[0],(unsigned long long)unrecorded[1]);
    if(selectedSite!=None)fprintf(f,"selected_cycles\t%llu\n",(unsigned long long)selectedCycles);
    for(unsigned k=0;k<kinds.size();++k)fprintf(f,"entry_%s\t%llu\n",kinds[k].c_str(),(unsigned long long)entryMarker[k]);
    for(auto &r:rootIncl)fprintf(f,"root_%s%s\t%llu\n",r.first>=1000?"nested_":"",kinds[r.first%1000].c_str(),(unsigned long long)r.second);
    fclose(f);
    return 0;
}
